### ISSUE TITLE
"TypeError: Failed to fetch" when restoring snapshot on fresh install

### ISSUE THREAD

**Issue by TheGroundZero** [home-assistant/operating-system#917]
**HassOS release with the issue:**

hassos_ova-4.14

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

Reinstalled HassOS in Proxmox using hassos_ova-4.14.qcow2 as new disk after latest install caused HA to no longer boot ([EUFI issue](https://pve.proxmox.com/wiki/Roadmap#_6.2_known_issues_ovmf)) and the [fix](https://pve.proxmox.com/wiki/OVMF/UEFI_Boot_Entries) didn't work (Proxmox no longer detected drive).

Followed Juan's [method of installing HA on Proxmox](https://www.juanmtech.com/install-proxmox-and-virtualize-home-assistant/).  
Downloaded qcow2.tar, unzipped, transfered qcow2 file, ran command to add as disk to HA instance, changed disks and booted from new disk.

![image](https://user-images.githubusercontent.com/2406013/96479119-07930700-1228-11eb-9cb2-a8696e1a20f8.png)
![image](https://user-images.githubusercontent.com/2406013/96480632-08c53380-122a-11eb-951c-20de2bdf195e.png)

Once Home Assistant has started, I select the option to restore from a previous snapshot.

![image](https://user-images.githubusercontent.com/2406013/96480745-2b574c80-122a-11eb-905e-35ca1ecef942.png)

I then select a fairly recent full snapshot to restore from.  
![image](https://user-images.githubusercontent.com/2406013/96480811-40cc7680-122a-11eb-9f3a-278dc50733bf.png)

As soon as it starts the restoration process, I get the error `TypeError: Failed to fetch`
![image](https://user-images.githubusercontent.com/2406013/96478986-dfa3a380-1227-11eb-8e18-5fd69a2d9ec9.png)

Refreshing the page, it seems that the webserver has died
![image](https://user-images.githubusercontent.com/2406013/96480992-740f0580-122a-11eb-8672-b5b142d7def2.png)

Rebooting the HA instance at this stage causes it to never come back online again.

At this moment, I'm stuck without a working copy of HA

**Comment by TheGroundZero** [comment]
Restored a VM back-up. Got it working again.

Won't be installing any updates to HA or rebooting any time soon.

**Comment by ludeeus** [comment]
This has been fixed in the frontend

**Comment by djoeney** [comment]
I’ve got the same message as titled, what worked for me is doing a “ha core restart”. After a few minutes I was happy to see my backed up image again.

**Comment by ManlyJack** [comment]
Why was this closed? It's still an issue.. I'm having it right now...

**Comment by Pr0gr4mm3r** [comment]
Same issue here! The second I load a recent snapshot (0.115) into my fresh install (0.116), I get the message: "TypeError: Failed to fetch". Nothing else seems to happen anymore, so the restore fails. Rebooting messes up the install which forces me to start all over: using balenaEtcher to burn the Home Assistant image onto my SD card. Sigh...

**Comment by bobvmierlo** [comment]
Same issue here, bricked my VM due to a full virtual disk. Trying to restore my snapshot from the onboarding page, but instantly get this error. After a while HA starts up but it's full of errors. The most important error seems to be that HA doesn't have internet connection so updating addon's and integrations that require internet access dont work

**Comment by danlun** [comment]
I have the same exactly. Clicking the link to restore from the startup screen after a fresh install and after choosing my tar-file and a little while I get "Failed to fetch". The process stops....

**Comment by bobvmierlo** [comment]
> Same issue here, bricked my VM due to a full virtual disk. Trying to restore my snapshot from the onboarding page, but instantly get this error. After a while HA starts up but it's full of errors. The most important error seems to be that HA doesn't have internet connection so updating addon's and integrations that require internet access dont work

Addition to my last comment:
I've got it to work, the issue with HA not having internet connection was due to my router still having the old MAC address linked to the static IP of the hassio VM.
So although it shows the error the restore proces seems to work if you just wait long enough. But the error is strange so it needs fixing anyway

**Comment by danlun** [comment]
Thanks bobvmierlo, that did help. I moved my tar-file from my network NAS to my PC (still in network) and for some reason it now worked and I got the question what to restore, chosed wipe and restore and after a while Im back up running. But I do agree, with the rror message delivered its hard to trust and just wait. Need a fix!

**Comment by ManlyJack** [comment]
Never got it to work, tried about 4 times but in the end just had to make a new user and upload the snapshot file in the snapshot section and restore it from inside home assistant.

**Comment by RichardvanGestel** [comment]
Same problem here.
HassOS 4.15 HomeAssistant 0.117.5
Supervisor 2020.11.0
"Upload snapshot" esults in an error message:  failed to fetch

**Comment by Madseason41** [comment]
Same here, tried on firefox and chrome, wired and wireless.

**Comment by albasee** [comment]
Same here...

**Comment by alexbelgium** [comment]
same here with latest hassio image

**Comment by chrissfoot** [comment]
This is happening to me with the latest 5.5 image. In fact, as long as I've been using HA it's never worked for me. I try on each new install and end up having to create the user and samba the backup in every time

**Comment by alexbelgium** [comment]
Well I found a way to make it work. Here is what I do :
- clean install and do initial config
- install Google drive backup addon and download snapshot
- restore all addons, wait until its restored
- restore folders for ssh, share and local addons, wait until its restored, then reboot
- restore configuration and wait 10 min for reboot

**Comment by mikewesner** [comment]
@ludeeus this issue should be reopened.  I just tried this use case today and the same issue exists.

**Comment by apple047** [comment]
it appears the fault persists  identical symptoms experiencing now

**Comment by TETZUO** [comment]
Issue is back again tried today
![image](https://user-images.githubusercontent.com/36467084/220818294-f9ff9d4c-12f9-4a9e-9878-cafec2f8377b.png)

**Comment by kitty99hub** [comment]
Same error for me today.... :(
Cannot restore backup on new HASSOS installation.

**Comment by TooTallOne** [comment]
Another same error here post!  Claimed that upload failed and 15 minutes later system restored.  This has been an error 2020?
